export const GEO_CODE_API_KEY = "AIzaSyCIKud8HrdeCkRdBRZ2oW835Hb3jSqMcvU";
export const API_GET_MUNICIPALITIES =
  "http://localhost:3000/address/municipalities";
export const API_GET_ADDRESS_BY_POSTCODE =
  "http://localhost:3000/address/postcode-number";
export const CHANGE_CURRENT_ADDRESS = "CHANGE_CURRENT_ADDRESS";
export const FORM_MUNICIPALITY = "MUNICIPALITY_SUGGESTED";
export const FORM_LOCATION = "FORM_LOCATION";
export const RESET_FORM_LOCATION = "RESET_FORM_LOCATION";
export const RESET_FORM_MUNICIPALITY = "RESET_FORM_MUNICIPALITY";
export const FORM_POSTCODE = "FORM_POSTCODE";
export const RESET_FORM_POSTCODE = "RESET_FORM_POSTCODE";
export const FORM_LOCATION_LOADING = "FORM_LOCATION_LOADING";
export const FORM_MUNICIPALITY_LOADING = "FORM_MUNICIPALITY_LOADING";
export const POSTCODE_MAX_DIGITS = 4;
